### ISSUE TITLE
[REFACTOR] Process Order를 Core에서 관리하도록 수정

### ISSUE THREAD

**Issue by Seongwon97** [team-go-higher/backend#100]
### 🚨 현재 코드의 문제점
현재는 Core-domain의 Process에는 Order가 존재하지 않고 Table에 저장할 때만 out-adapter에서 order 필드의 값을 할당해서 저장해줍니다. 또한 조회를 할때도 Order값을 통해 Process를 정렬하여 `List<Process>`의 형태로 Core로 넘겨주고 있습니다.
이러한 구조의 문제는 아래와 같습니다.
1. Process의 order값의 할당을 core가 아닌 out-adapter가 관리한다. 
   > 📌 해당 문제는 order의 값을 저장해야하는 관심사는 데이터베이스지, core에서는 order의 존재를 알지 않아도 괜찮다 생각했습니다. 하지만 이것은 단순히 저장하고 조회만 할 때에는 문제가 되지 않습니다. 하지만 전형 과정에 변동이 생기면 아래와 같이 곤란해집니다.
2. 전형 과정을 추가할 경우, out-adapter에 order의 값을 새롭게 할당하고 조정하는 비즈니스 로직이 들어가게 된다.
   > 📌 예를 들어 1-2-3-4-5의 과정이 있는데 2-3사이에 과정이 추가될 경우, 현재의 구조대로면 out-adapter는 `List<Process>`형태의 값을 받아서 어떤 데이터가 추가된 것이고, 어떤 데이터에 변동이 발생하였고, 어떤 데이터가 삭제되었는지 등을 판단하여 쿼리를 날려야합니다. 즉, core에 있어야 할 비즈니스 로직이 out-adapter가 갖게 됩니다.

### 🎯 작업 내용
위의 문제를 해결하고자 아래의 작업을 진행하려 합니다.
- core-domain의 `Process`클래스에 `order`필드 추가
- order 번호의 할당을 out-adapter가 아닌 core에서 하도록 수정

**Comment by Byeongju-Kong** [comment]
왜 ProcessOrder의 할당 로직을 domain이 아닌 core-application에 위치시키신건가요?

**Comment by Seongwon97** [comment]
@Byeongju-Kong 
> 왜 ProcessOrder의 할당 로직을 domain이 아닌 core-application에 위치시키신건가요?

아하 저는 해당 로직을 core부분으로 옮겨야한다는 것을 core-application으로 기재하여 혼란을 드렸군요😭😭
해당 Issue를 작업한 PR에서는 domain에 Processes라는 일급 컬렉션을 만들어서 해당 클래스에서 order를 할당하도록 했습니다!!
